// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "../ui.h"

void ui_batteryScreen_screen_init(void)
{
ui_batteryScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_batteryScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_batteryScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_batteryScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_batteryScreen, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SBattVArc = lv_arc_create(ui_batteryScreen);
lv_obj_set_width( ui_SBattVArc, 430);
lv_obj_set_height( ui_SBattVArc, 430);
lv_obj_set_align( ui_SBattVArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SBattVArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_SBattVArc, 9,15);
lv_arc_set_value(ui_SBattVArc, 1284);
lv_arc_set_bg_angles(ui_SBattVArc,135,260);
lv_obj_set_style_arc_color(ui_SBattVArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SBattVArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SBattVArc, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SBattVArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SBattVArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SBattVArc, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SBattVArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SBattVArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SA1Arc = lv_arc_create(ui_batteryScreen);
lv_obj_set_width( ui_SA1Arc, 430);
lv_obj_set_height( ui_SA1Arc, 430);
lv_obj_set_align( ui_SA1Arc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SA1Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_SA1Arc, -100,100);
lv_arc_set_value(ui_SA1Arc, -13);
lv_arc_set_bg_angles(ui_SA1Arc,280,45);
lv_arc_set_mode(ui_SA1Arc, LV_ARC_MODE_SYMMETRICAL);
lv_obj_set_style_arc_color(ui_SA1Arc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SA1Arc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SA1Arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SA1Arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SA1Arc, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SA1Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SA1Arc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_HBattVArc = lv_arc_create(ui_batteryScreen);
lv_obj_set_width( ui_HBattVArc, 370);
lv_obj_set_height( ui_HBattVArc, 370);
lv_obj_set_align( ui_HBattVArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HBattVArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_HBattVArc, 9,15);
lv_arc_set_value(ui_HBattVArc, 15);
lv_arc_set_bg_angles(ui_HBattVArc,135,260);
lv_obj_set_style_arc_color(ui_HBattVArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HBattVArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HBattVArc, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_HBattVArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HBattVArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HBattVArc, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HBattVArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HBattVArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_HA2Arc = lv_arc_create(ui_batteryScreen);
lv_obj_set_width( ui_HA2Arc, 370);
lv_obj_set_height( ui_HA2Arc, 370);
lv_obj_set_align( ui_HA2Arc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HA2Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_HA2Arc, -100,100);
lv_arc_set_value(ui_HA2Arc, -100);
lv_arc_set_bg_angles(ui_HA2Arc,280,45);
lv_arc_set_mode(ui_HA2Arc, LV_ARC_MODE_SYMMETRICAL);
lv_obj_set_style_arc_color(ui_HA2Arc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HA2Arc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_HA2Arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HA2Arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HA2Arc, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HA2Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HA2Arc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_battVLabelSensor = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_battVLabelSensor, LV_SIZE_CONTENT);  /// 140
lv_obj_set_height( ui_battVLabelSensor, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_battVLabelSensor, -20 );
lv_obj_set_y( ui_battVLabelSensor, -96 );
lv_obj_set_align( ui_battVLabelSensor, LV_ALIGN_CENTER );
lv_label_set_text(ui_battVLabelSensor,"15.00");
lv_obj_clear_flag( ui_battVLabelSensor, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_battVLabelSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_battVLabelSensor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_battVLabelSensor, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_battVLabelSensor, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_battALabelSensor = lv_label_create(ui_batteryScreen);
lv_obj_set_height( ui_battALabelSensor, 45);
lv_obj_set_width( ui_battALabelSensor, LV_SIZE_CONTENT);  /// 140
lv_obj_set_x( ui_battALabelSensor, -30 );
lv_obj_set_y( ui_battALabelSensor, 80 );
lv_obj_set_align( ui_battALabelSensor, LV_ALIGN_CENTER );
lv_label_set_text(ui_battALabelSensor,"-12.84");
lv_obj_clear_flag( ui_battALabelSensor, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_battALabelSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_battALabelSensor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_battALabelSensor, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_battALabelSensor, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryVLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_batteryVLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryVLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryVLabel, 71 );
lv_obj_set_y( ui_batteryVLabel, -96 );
lv_obj_set_align( ui_batteryVLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryVLabel,"V");
lv_obj_clear_flag( ui_batteryVLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_batteryVLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batteryVLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryVLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryALabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_batteryALabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryALabel, 70 );
lv_obj_set_y( ui_batteryALabel, 84 );
lv_obj_set_align( ui_batteryALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryALabel,"A");
lv_obj_clear_flag( ui_batteryALabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_batteryALabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batteryALabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryALabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_startBatteryLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_startBatteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_startBatteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_startBatteryLabel, -60 );
lv_obj_set_y( ui_startBatteryLabel, 4 );
lv_obj_set_align( ui_startBatteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_startBatteryLabel,"START");
lv_obj_clear_flag( ui_startBatteryLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_startBatteryLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_startBatteryLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_startBatteryLabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryIcon = lv_img_create(ui_batteryScreen);
lv_img_set_src(ui_batteryIcon, &ui_img_2056808699);
lv_obj_set_width( ui_batteryIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryIcon, 60 );
lv_obj_set_y( ui_batteryIcon, 0 );
lv_obj_set_align( ui_batteryIcon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batteryIcon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_batteryIcon,220);

ui_aeIconBatteryScreen1 = lv_img_create(ui_batteryScreen);
lv_img_set_src(ui_aeIconBatteryScreen1, &ui_img_ae_white_128_png);
lv_obj_set_width( ui_aeIconBatteryScreen1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aeIconBatteryScreen1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_aeIconBatteryScreen1, 0 );
lv_obj_set_y( ui_aeIconBatteryScreen1, 170 );
lv_obj_set_align( ui_aeIconBatteryScreen1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_aeIconBatteryScreen1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_aeIconBatteryScreen1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_aeIconBatteryScreen1,150);

lv_obj_add_event_cb(ui_aeIconBatteryScreen1, ui_event_aeIconBatteryScreen1, LV_EVENT_ALL, NULL);

}
