// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef UI_BATTERYSCREEN_H
#define UI_BATTERYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_batteryScreen
extern void ui_batteryScreen_screen_init(void);
extern void ui_batteryScreen_screen_destroy(void);
extern lv_obj_t *ui_batteryScreen;
extern lv_obj_t *ui_SBattVArc;
extern lv_obj_t *ui_SA1Arc;
extern lv_obj_t *ui_battVLabelSensor;
extern lv_obj_t *ui_battALabelSensor;
extern lv_obj_t *ui_batteryVLabel;
extern lv_obj_t *ui_batteryALabel;
extern lv_obj_t *ui_startBatteryLabel;
extern void ui_event_aeIconBatteryScreen1( lv_event_t * e);
extern lv_obj_t *ui_aeIconBatteryScreen1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_startBatteryTime;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

