// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "../ui.h"
#include "Arduino.h"

extern String SSID;
extern String PWD;
extern bool wifiSetToOn;

void ui_bootInitialScreen_screen_init(void)
{
ui_bootInitialScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_bootInitialScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_bootInitialScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bootInitialScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner1 = lv_spinner_create(ui_bootInitialScreen,1000,90);
lv_obj_set_width( ui_Spinner1, 480);
lv_obj_set_height( ui_Spinner1, 480);
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Spinner1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_feedbackLabel = lv_label_create(ui_bootInitialScreen);
lv_obj_set_width( ui_feedbackLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_feedbackLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_feedbackLabel, 0 );
lv_obj_set_y( ui_feedbackLabel, -125 );
lv_obj_set_align( ui_feedbackLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_feedbackLabel,"WiFi: UNKNOWN");
lv_obj_set_style_text_color(ui_feedbackLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_feedbackLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_feedbackLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_feedbackLabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiIcon = lv_img_create(ui_bootInitialScreen);
if (wifiSetToOn)
{
    lv_img_set_src(ui_wifiIcon, &ui_img_807091229); // WiFi on
}
else
{
    lv_img_set_src(ui_wifiIcon, &ui_img_2104900491); // WiFi off
}
lv_obj_set_width( ui_wifiIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiIcon, -135 );
lv_obj_set_y( ui_wifiIcon, -4 );
lv_obj_set_align( ui_wifiIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_wifiIcon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_settingsIcon = lv_img_create(ui_bootInitialScreen);
lv_img_set_src(ui_settingsIcon, &ui_img_501072417);
lv_obj_set_width( ui_settingsIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingsIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_settingsIcon, 136 );
lv_obj_set_y( ui_settingsIcon, -4 );
lv_obj_set_align( ui_settingsIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settingsIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_settingsIcon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_aeLandingIcon = lv_img_create(ui_bootInitialScreen);
lv_img_set_src(ui_aeLandingIcon, &ui_img_ae_white_128_png);
lv_obj_set_width( ui_aeLandingIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aeLandingIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_aeLandingIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_aeLandingIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_aeLandingIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SSIDLabel = lv_label_create(ui_bootInitialScreen);
lv_obj_set_width( ui_SSIDLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SSIDLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SSIDLabel, -80 );
lv_obj_set_y( ui_SSIDLabel, -90 );
lv_obj_set_align( ui_SSIDLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SSIDLabel,"Network SSID:");
lv_obj_add_flag( ui_SSIDLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SSIDLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SSIDLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SSIDInputText = lv_textarea_create(ui_bootInitialScreen);
lv_obj_set_width( ui_SSIDInputText, lv_pct(80));
lv_obj_set_height( ui_SSIDInputText, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_SSIDInputText, 0 );
lv_obj_set_y( ui_SSIDInputText, -58 );
lv_obj_set_align( ui_SSIDInputText, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_SSIDInputText,64);
if (SSID != "none")
{
    lv_textarea_set_text(ui_SSIDInputText,SSID.c_str()); 
}
else
{
    lv_textarea_set_text(ui_SSIDInputText,"Enter SSID Name...");
}
lv_textarea_set_one_line(ui_SSIDInputText,true);
lv_obj_add_flag( ui_SSIDInputText, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SSIDInputText, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SSIDInputText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDInputText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SSIDInputText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SSIDInputText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_SSIDInputText, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDInputText, 255, LV_PART_CURSOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SSIDInputText, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SSIDInputText, 255, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_SSIDInputText, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDInputText, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_SSIDPasswordLabel = lv_label_create(ui_bootInitialScreen);
lv_obj_set_width( ui_SSIDPasswordLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SSIDPasswordLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SSIDPasswordLabel, -80 );
lv_obj_set_y( ui_SSIDPasswordLabel, 15 );
lv_obj_set_align( ui_SSIDPasswordLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SSIDPasswordLabel,"SSID Password:");
lv_obj_add_flag( ui_SSIDPasswordLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SSIDPasswordLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SSIDPasswordLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDPasswordLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SSIDPasswordInputText = lv_textarea_create(ui_bootInitialScreen);
lv_obj_set_width( ui_SSIDPasswordInputText, lv_pct(80));
lv_obj_set_height( ui_SSIDPasswordInputText, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_SSIDPasswordInputText, 0 );
lv_obj_set_y( ui_SSIDPasswordInputText, 48 );
lv_obj_set_align( ui_SSIDPasswordInputText, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_SSIDPasswordInputText,64);
if (PWD != "none")
{
    lv_textarea_set_text(ui_SSIDPasswordInputText,PWD.c_str());
}
else
{
    lv_textarea_set_text(ui_SSIDPasswordInputText,"Enter SSID Password...");
}
lv_textarea_set_one_line(ui_SSIDPasswordInputText,true);
lv_obj_add_flag( ui_SSIDPasswordInputText, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SSIDPasswordInputText, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SSIDPasswordInputText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDPasswordInputText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SSIDPasswordInputText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SSIDPasswordInputText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_SSIDPasswordInputText, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDPasswordInputText, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SSIDPasswordInputText, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SSIDPasswordInputText, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_SSIDPasswordInputText, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDPasswordInputText, 255, LV_PART_CURSOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SSIDPasswordInputText, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SSIDPasswordInputText, 255, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_SSIDPasswordInputText, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SSIDPasswordInputText, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_Keyboard = lv_keyboard_create(ui_bootInitialScreen);
lv_obj_set_width( ui_Keyboard, 470);
lv_obj_set_height( ui_Keyboard, 160);
lv_obj_set_x( ui_Keyboard, 0 );
lv_obj_set_y( ui_Keyboard, 6 );
lv_obj_set_align( ui_Keyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_y( ui_Keyboard, 6 );
lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Keyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Keyboard, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Keyboard, 1, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Keyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Keyboard, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Keyboard, 1, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Keyboard, 0, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Keyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Keyboard, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_landingBackButton = lv_label_create(ui_bootInitialScreen);
lv_obj_set_width( ui_landingBackButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_landingBackButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_landingBackButton, 0 );
lv_obj_set_y( ui_landingBackButton, 160 );
lv_obj_set_align( ui_landingBackButton, LV_ALIGN_CENTER );
lv_label_set_text(ui_landingBackButton,"Back");
lv_obj_add_flag( ui_landingBackButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_landingBackButton, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_landingBackButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_landingBackButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_landingBackButton, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_landingBackButton, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_landingBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_landingBackButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_landingBackButton, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_landingBackButton, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_landingBackButton, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_landingBackButton, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aeLandingBottomLabel = lv_label_create(ui_bootInitialScreen);
lv_obj_set_width( ui_aeLandingBottomLabel, 199);
lv_obj_set_height( ui_aeLandingBottomLabel, 25);
lv_obj_set_x( ui_aeLandingBottomLabel, 6 );
lv_obj_set_y( ui_aeLandingBottomLabel, 140 );
lv_obj_set_align( ui_aeLandingBottomLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_aeLandingBottomLabel,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_aeLandingBottomLabel,"Waiting for AE-Mesh data...");
lv_obj_set_style_text_color(ui_aeLandingBottomLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_aeLandingBottomLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_aeLandingBottomLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_aeLandingBottomLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_aeLandingBottomLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_aeLandingBottomLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_aeLandingBottomLabel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_aeLandingBottomLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_aeLandingBottomLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_aeLandingBottomLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aeLandingBottomIcon = lv_img_create(ui_bootInitialScreen);
lv_img_set_src(ui_aeLandingBottomIcon, &ui_img_1917549703);
lv_obj_set_width( ui_aeLandingBottomIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aeLandingBottomIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_aeLandingBottomIcon, -81 );
lv_obj_set_y( ui_aeLandingBottomIcon, 136 );
lv_obj_set_align( ui_aeLandingBottomIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_aeLandingBottomIcon, LV_OBJ_FLAG_ADV_HITTEST| LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_aeLandingBottomIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_aeLandingBottomIcon,128);
lv_obj_add_event_cb(ui_wifiIcon, ui_event_wifiIcon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settingsIcon, ui_event_settingsIcon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_aeLandingIcon, ui_event_aeLandingIcon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SSIDInputText, ui_event_SSIDInputText, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SSIDPasswordInputText, ui_event_SSIDPasswordInputText, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_landingBackButton, ui_event_landingBackButton, LV_EVENT_ALL, NULL);

}
