// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "../ui.h"

void ui_coolantScreen_screen_init(void)
{
ui_coolantScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_coolantScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_coolantScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_coolantScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_coolantScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_coolantScreen, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_coolantTemp = lv_arc_create(ui_coolantScreen);
lv_obj_set_width( ui_coolantTemp, 430);
lv_obj_set_height( ui_coolantTemp, 430);
lv_obj_set_align( ui_coolantTemp, LV_ALIGN_CENTER );
lv_arc_set_range(ui_coolantTemp, 40,150);
lv_arc_set_value(ui_coolantTemp, 96);
lv_arc_set_bg_angles(ui_coolantTemp,135,260);
lv_obj_set_style_arc_color(ui_coolantTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_coolantTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_coolantTemp, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_coolantTemp, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_coolantTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_coolantTemp, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_coolantTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_coolantTemp, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_coolantPressure = lv_arc_create(ui_coolantScreen);
lv_obj_set_width( ui_coolantPressure, 430);
lv_obj_set_height( ui_coolantPressure, 430);
lv_obj_set_align( ui_coolantPressure, LV_ALIGN_CENTER );
lv_arc_set_range(ui_coolantPressure, 10,90);
lv_arc_set_value(ui_coolantPressure, 50);
lv_arc_set_bg_angles(ui_coolantPressure,280,45);
lv_arc_set_mode(ui_coolantPressure, LV_ARC_MODE_REVERSE);
lv_obj_set_style_arc_color(ui_coolantPressure, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_coolantPressure, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_coolantPressure, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_coolantPressure, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_coolantPressure, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_coolantPressure, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_coolantPressure, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_coolantPressure, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_coolantTempLabelSensor = lv_label_create(ui_coolantScreen);
lv_obj_set_width( ui_coolantTempLabelSensor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_coolantTempLabelSensor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_coolantTempLabelSensor, -40 );
lv_obj_set_y( ui_coolantTempLabelSensor, -96 );
lv_obj_set_align( ui_coolantTempLabelSensor, LV_ALIGN_CENTER );
lv_label_set_text(ui_coolantTempLabelSensor,"96");
lv_obj_set_style_text_color(ui_coolantTempLabelSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_coolantTempLabelSensor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_coolantTempLabelSensor, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_coolantTempLabelSensor, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_coolantPressureLabelSensor = lv_label_create(ui_coolantScreen);
lv_obj_set_height( ui_coolantPressureLabelSensor, 45);
lv_obj_set_width( ui_coolantPressureLabelSensor, LV_SIZE_CONTENT);  /// 140
lv_obj_set_x( ui_coolantPressureLabelSensor, -40 );
lv_obj_set_y( ui_coolantPressureLabelSensor, 80 );
lv_obj_set_align( ui_coolantPressureLabelSensor, LV_ALIGN_CENTER );
lv_label_set_text(ui_coolantPressureLabelSensor,"45");
lv_obj_set_style_text_color(ui_coolantPressureLabelSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_coolantPressureLabelSensor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_coolantPressureLabelSensor, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_coolantPressureLabelSensor, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_coolantTempCLabel = lv_label_create(ui_coolantScreen);
lv_obj_set_width( ui_coolantTempCLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_coolantTempCLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_coolantTempCLabel, 20 );
lv_obj_set_y( ui_coolantTempCLabel, -96 );
lv_obj_set_align( ui_coolantTempCLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_coolantTempCLabel,"C");
lv_obj_set_style_text_color(ui_coolantTempCLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_coolantTempCLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_coolantTempCLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_coolantTempPressureLabel = lv_label_create(ui_coolantScreen);
lv_obj_set_width( ui_coolantTempPressureLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_coolantTempPressureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_coolantTempPressureLabel, 45 );
lv_obj_set_y( ui_coolantTempPressureLabel, 84 );
lv_obj_set_align( ui_coolantTempPressureLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_coolantTempPressureLabel,"PSI");
lv_obj_set_style_text_color(ui_coolantTempPressureLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_coolantTempPressureLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_coolantTempPressureLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_coolantOilIconScreen = lv_img_create(ui_coolantScreen);
lv_img_set_src(ui_coolantOilIconScreen, &ui_img_ae_white_128_png);
lv_obj_set_width( ui_coolantOilIconScreen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_coolantOilIconScreen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_coolantOilIconScreen, 0 );
lv_obj_set_y( ui_coolantOilIconScreen, 170 );
lv_obj_set_align( ui_coolantOilIconScreen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_coolantOilIconScreen, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_coolantOilIconScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_coolantOilIconScreen,150);

ui_coolantIcon = lv_img_create(ui_coolantScreen);
lv_img_set_src(ui_coolantIcon, &ui_img_2930172);
lv_obj_set_width( ui_coolantIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_coolantIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_coolantIcon, -5 );
lv_obj_set_y( ui_coolantIcon, -10 );
lv_obj_set_align( ui_coolantIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_coolantIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_coolantIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_coolantIcon,170);

lv_obj_add_event_cb(ui_coolantOilIconScreen, ui_event_coolantOilIconScreen, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_coolantScreen, ui_event_coolantScreen, LV_EVENT_ALL, NULL);

}
