// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef UI_COOLANTSCREEN_H
#define UI_COOLANTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_coolantScreen
extern void ui_coolantScreen_screen_init(void);
extern void ui_coolantScreen_screen_destroy(void);
extern lv_obj_t *ui_coolantScreen;
extern lv_obj_t *ui_coolantTemp;
extern lv_obj_t *ui_coolantPressure;
extern lv_obj_t *ui_coolantTempLabelSensor;
extern lv_obj_t *ui_coolantPressureLabelSensor;
extern lv_obj_t *ui_coolantTempCLabel;
extern lv_obj_t *ui_coolantTempPressureLabel;
extern void ui_event_coolantOilIconScreen( lv_event_t * e);
extern lv_obj_t *ui_coolantOilIconScreen;
extern lv_obj_t *ui_coolantIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

