// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef UI_OILSCREEN_H
#define UI_OILSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_oilScreen
extern void ui_oilScreen_screen_init(void);
extern void ui_oilScreen_screen_destroy(void);
extern lv_obj_t *ui_oilScreen;
extern lv_obj_t *ui_oilTemp;
extern lv_obj_t *ui_oilPressure;
extern lv_obj_t *ui_oilTempLabelSensor;
extern lv_obj_t *ui_oilPressureLabelSensor;
extern lv_obj_t *ui_oilTempCLabel;
extern lv_obj_t *ui_oilTempPressureLabel;
extern void ui_event_aeOilIconScreen( lv_event_t * e);
extern lv_obj_t *ui_aeOilIconScreen;
extern lv_obj_t *ui_oilIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

