// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Screen2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Screen2, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SBatt1 = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_SBatt1, 430);
lv_obj_set_height( ui_SBatt1, 430);
lv_obj_set_align( ui_SBatt1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_SBatt1, 9,15);
lv_arc_set_value(ui_SBatt1, 15);
lv_arc_set_bg_angles(ui_SBatt1,120,270);
lv_obj_set_style_arc_color(ui_SBatt1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SBatt1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SBatt1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SBatt1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SBatt1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SBatt1, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SBatt1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SBatt1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SA1 = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_SA1, 430);
lv_obj_set_height( ui_SA1, 430);
lv_obj_set_align( ui_SA1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_SA1, -100,100);
lv_arc_set_value(ui_SA1, 100);
lv_arc_set_bg_angles(ui_SA1,270,45);
lv_arc_set_mode(ui_SA1, LV_ARC_MODE_SYMMETRICAL);
lv_obj_set_style_arc_color(ui_SA1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SA1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SA1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SA1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SA1, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SA1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SA1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_HBatt1 = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_HBatt1, 370);
lv_obj_set_height( ui_HBatt1, 370);
lv_obj_set_align( ui_HBatt1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_HBatt1, 9,15);
lv_arc_set_value(ui_HBatt1, 14);
lv_arc_set_bg_angles(ui_HBatt1,120,270);
lv_obj_set_style_arc_color(ui_HBatt1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HBatt1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HBatt1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_HBatt1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HBatt1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HBatt1, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HBatt1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HBatt1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_HA2 = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_HA2, 370);
lv_obj_set_height( ui_HA2, 370);
lv_obj_set_align( ui_HA2, LV_ALIGN_CENTER );
lv_arc_set_range(ui_HA2, -100,100);
lv_arc_set_value(ui_HA2, 100);
lv_arc_set_bg_angles(ui_HA2,270,45);
lv_arc_set_mode(ui_HA2, LV_ARC_MODE_SYMMETRICAL);
lv_obj_set_style_arc_color(ui_HA2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HA2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_HA2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HA2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HA2, 14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HA2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HA2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_BattVLabel = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_BattVLabel, LV_SIZE_CONTENT);  /// 140
lv_obj_set_height( ui_BattVLabel, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_BattVLabel, -17 );
lv_obj_set_y( ui_BattVLabel, -75 );
lv_obj_set_align( ui_BattVLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BattVLabel,"12.84");
lv_obj_set_style_text_color(ui_BattVLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BattVLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BattVLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BattVLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BattALabel = lv_label_create(ui_Screen2);
lv_obj_set_height( ui_BattALabel, 45);
lv_obj_set_width( ui_BattALabel, LV_SIZE_CONTENT);  /// 140
lv_obj_set_x( ui_BattALabel, -26 );
lv_obj_set_y( ui_BattALabel, 75 );
lv_obj_set_align( ui_BattALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BattALabel,"-12.84");
lv_obj_set_style_text_color(ui_BattALabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BattALabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BattALabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BattALabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VLabel = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_VLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VLabel, 60 );
lv_obj_set_y( ui_VLabel, -75 );
lv_obj_set_align( ui_VLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_VLabel,"V");
lv_obj_set_style_text_color(ui_VLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_VLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_VLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ALabel = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_ALabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ALabel, 60 );
lv_obj_set_y( ui_ALabel, 79 );
lv_obj_set_align( ui_ALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ALabel,"A");
lv_obj_set_style_text_color(ui_ALabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ALabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ALabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatteryLabel = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_BatteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryLabel, -2 );
lv_obj_set_y( ui_BatteryLabel, -130 );
lv_obj_set_align( ui_BatteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryLabel,"START");
lv_obj_set_style_text_color(ui_BatteryLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatteryLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatteryLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Image1, &ui_img_ae_white_96_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, 170 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,200);

ui_Image2 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Image2, &ui_img_2056808699);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,220);

lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
