// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef UI_TURBOEXHAUSTSCREEN_H
#define UI_TURBOEXHAUSTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_turboExhaustScreen
extern void ui_turboExhaustScreen_screen_init(void);
extern void ui_turboExhaustScreen_screen_destroy(void);
extern lv_obj_t *ui_turboExhaustScreen;
extern lv_obj_t *ui_egtTemp;
extern lv_obj_t *ui_turboPressure;
extern lv_obj_t *ui_egtTempLabelSensor;
extern lv_obj_t *ui_turboPressureLabelSensor;
extern lv_obj_t *ui_egtTempCLabel;
extern lv_obj_t *ui_turboTempPressureLabel;
extern void ui_event_egtIconScreen( lv_event_t * e);
extern lv_obj_t *ui_egtIconScreen;
extern lv_obj_t *ui_turboIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

