// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef _AE_52MM_GAUGE_UI_H
#define _AE_52MM_GAUGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_bootInitialScreen.h"
#include "ui_batteryScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_807091229);   // assets/ae-wifi-96.png
LV_IMG_DECLARE( ui_img_501072417);   // assets/ae-cog-96.png
LV_IMG_DECLARE( ui_img_ae_white_128_png);   // assets/ae_white_128.png
LV_IMG_DECLARE( ui_img_1917549703);   // assets/ae-map-marker-96.png
LV_IMG_DECLARE( ui_img_2056808699);   // assets/ae-gauge-battery-128.png
LV_IMG_DECLARE( ui_img_2930172);   // assets/ae-coolant-128.png
LV_IMG_DECLARE( ui_img_2022370193);   // assets/ae-esp-now-96.png
LV_IMG_DECLARE( ui_img_1749172309);   // assets/ae-gauge-settings-96.png
LV_IMG_DECLARE( ui_img_2105704960);   // assets/ae-low-rssi-96.png
LV_IMG_DECLARE( ui_img_1105680357);   // assets/ae-oil-temp-128.png
LV_IMG_DECLARE( ui_img_539538216);   // assets/ae-settings-erase-96.png
LV_IMG_DECLARE( ui_img_1209853138);   // assets/ae-turbo-128.png
LV_IMG_DECLARE( ui_img_2104900491);   // assets/ae-wifi-off-96.png
LV_IMG_DECLARE( ui_img_943648365);   // assets/ae-wifi-settings-96.png

// FONTS
LV_FONT_DECLARE( ui_font_AE64BOLD);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
