// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef _AE_52MM_GAUGE_UI_H
#define _AE_52MM_GAUGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Spinner1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_SBatt1;
extern lv_obj_t *ui_SA1;
extern lv_obj_t *ui_HBatt1;
extern lv_obj_t *ui_HA2;
extern lv_obj_t *ui_BattVLabel;
extern lv_obj_t *ui_BattALabel;
extern lv_obj_t *ui_VLabel;
extern lv_obj_t *ui_ALabel;
extern lv_obj_t *ui_BatteryLabel;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ae_white_128_png);   // assets/ae_white_128.png
LV_IMG_DECLARE( ui_img_2056808699);   // assets/ae-gauge-battery-128.png
LV_IMG_DECLARE( ui_img_ae_white_96_png);   // assets/ae_white_96.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
