// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef _AE_52MM_GAUGE_UI_H
#define _AE_52MM_GAUGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_bootInitialScreen
void ui_bootInitialScreen_screen_init(void);
extern lv_obj_t *ui_bootInitialScreen;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image3;
// SCREEN: ui_batteryScreen
void ui_batteryScreen_screen_init(void);
extern lv_obj_t *ui_batteryScreen;
extern lv_obj_t *ui_SBattVArc;
extern lv_obj_t *ui_SA1Arc;
extern lv_obj_t *ui_HBattVArc;
extern lv_obj_t *ui_HA2Arc;
extern lv_obj_t *ui_battVLabelSensor;
extern lv_obj_t *ui_battALabelSensor;
extern lv_obj_t *ui_batteryVLabel;
extern lv_obj_t *ui_batteryALabel;
extern lv_obj_t *ui_startBatteryLabel;
extern lv_obj_t *ui_batteryIcon;
void ui_event_aeIconBatteryScreen1( lv_event_t * e);
extern lv_obj_t *ui_aeIconBatteryScreen1;
// SCREEN: ui_oilScreen
void ui_oilScreen_screen_init(void);
extern lv_obj_t *ui_oilScreen;
extern lv_obj_t *ui_oilTemp;
extern lv_obj_t *ui_oilPressure;
extern lv_obj_t *ui_oilTempLabelSensor;
extern lv_obj_t *ui_oilPressureLabelSensor;
extern lv_obj_t *ui_oilTempCLabel;
extern lv_obj_t *ui_oilTempPressureLabel;
void ui_event_aeOilIconScreen( lv_event_t * e);
extern lv_obj_t *ui_aeOilIconScreen;
extern lv_obj_t *ui_oilIcon;
// SCREEN: ui_coolantScreen
void ui_coolantScreen_screen_init(void);
extern lv_obj_t *ui_coolantScreen;
extern lv_obj_t *ui_coolantTemp;
extern lv_obj_t *ui_coolantPressure;
extern lv_obj_t *ui_coolantTempLabelSensor;
extern lv_obj_t *ui_coolantPressureLabelSensor;
extern lv_obj_t *ui_coolantTempCLabel;
extern lv_obj_t *ui_coolantTempPressureLabel;
void ui_event_coolantOilIconScreen( lv_event_t * e);
extern lv_obj_t *ui_coolantOilIconScreen;
extern lv_obj_t *ui_coolantIcon;
// SCREEN: ui_turboExhaustScreen
void ui_turboExhaustScreen_screen_init(void);
extern lv_obj_t *ui_turboExhaustScreen;
extern lv_obj_t *ui_egtTemp;
extern lv_obj_t *ui_turboPressure;
extern lv_obj_t *ui_egtTempLabelSensor;
extern lv_obj_t *ui_turboPressureLabelSensor;
extern lv_obj_t *ui_egtTempCLabel;
extern lv_obj_t *ui_turboTempPressureLabel;
void ui_event_egtIconScreen( lv_event_t * e);
extern lv_obj_t *ui_egtIconScreen;
extern lv_obj_t *ui_turboIcon;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ae_white_128_png);   // assets/ae_white_128.png
LV_IMG_DECLARE( ui_img_807091229);   // assets/ae-wifi-96.png
LV_IMG_DECLARE( ui_img_943648365);   // assets/ae-wifi-settings-96.png
LV_IMG_DECLARE( ui_img_2056808699);   // assets/ae-gauge-battery-128.png
LV_IMG_DECLARE( ui_img_1105680357);   // assets/ae-oil-temp-128.png
LV_IMG_DECLARE( ui_img_2930172);   // assets/ae-coolant-128.png
LV_IMG_DECLARE( ui_img_1209853138);   // assets/ae-turbo-128.png
LV_IMG_DECLARE( ui_img_2104900491);   // assets/ae-wifi-off-96.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
