// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "ui.h"

lv_obj_t *ui_batteryScreen = NULL;lv_obj_t *ui_SBattVArc = NULL;lv_obj_t *ui_SA1Arc = NULL;lv_obj_t *ui_battVLabelSensor = NULL;lv_obj_t *ui_battALabelSensor = NULL;lv_obj_t *ui_batteryVLabel = NULL;lv_obj_t *ui_batteryALabel = NULL;lv_obj_t *ui_startBatteryLabel = NULL;lv_obj_t *ui_aeIconBatteryScreen1 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_BatteryTime = NULL;lv_obj_t *ui_SOCLabel = NULL;lv_obj_t *ui_meshIndicator = NULL;lv_obj_t *ui_BarDayLabel = NULL;lv_obj_t *ui_BarDayBottomLabel = NULL;lv_obj_t *ui_BarWeekLabel = NULL;lv_obj_t *ui_BarWeekBottomLabel = NULL;
// event funtions
void ui_event_aeIconBatteryScreen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_bootInitialScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_bootInitialScreen_screen_init);
}
}

// build funtions

void ui_batteryScreen_screen_init(void)
{
ui_batteryScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_batteryScreen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_batteryScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_batteryScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_batteryScreen, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SBattVArc = lv_arc_create(ui_batteryScreen);
lv_obj_set_width( ui_SBattVArc, 480);
lv_obj_set_height( ui_SBattVArc, 480);
lv_obj_set_align( ui_SBattVArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SBattVArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_SBattVArc, 116,144);
lv_arc_set_value(ui_SBattVArc, 144);
lv_arc_set_bg_angles(ui_SBattVArc,45,315);
lv_arc_set_rotation(ui_SBattVArc,90);
lv_obj_set_style_arc_color(ui_SBattVArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SBattVArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SBattVArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SBattVArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SBattVArc, 30, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SBattVArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SBattVArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SA1Arc = lv_arc_create(ui_batteryScreen);
lv_obj_set_width( ui_SA1Arc, 415);
lv_obj_set_height( ui_SA1Arc, 415);
lv_obj_set_align( ui_SA1Arc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SA1Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_SA1Arc, -20,20);
lv_arc_set_value(ui_SA1Arc, 3);
lv_arc_set_bg_angles(ui_SA1Arc,45,315);
lv_arc_set_mode(ui_SA1Arc, LV_ARC_MODE_SYMMETRICAL);
lv_arc_set_rotation(ui_SA1Arc,90);
lv_obj_set_style_arc_color(ui_SA1Arc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SA1Arc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SA1Arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SA1Arc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SA1Arc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SA1Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SA1Arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_battVLabelSensor = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_battVLabelSensor, LV_SIZE_CONTENT);  /// 140
lv_obj_set_height( ui_battVLabelSensor, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_battVLabelSensor, -100 );
lv_obj_set_y( ui_battVLabelSensor, -80 );
lv_obj_set_align( ui_battVLabelSensor, LV_ALIGN_CENTER );
lv_label_set_text(ui_battVLabelSensor,"14.60");
lv_obj_clear_flag( ui_battVLabelSensor, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_battVLabelSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_battVLabelSensor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_battVLabelSensor, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_battALabelSensor = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_battALabelSensor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_battALabelSensor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_battALabelSensor, 100 );
lv_obj_set_y( ui_battALabelSensor, -80 );
lv_obj_set_align( ui_battALabelSensor, LV_ALIGN_CENTER );
lv_label_set_text(ui_battALabelSensor," 03.00");
lv_obj_clear_flag( ui_battALabelSensor, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_battALabelSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_battALabelSensor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_battALabelSensor, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_battALabelSensor, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryVLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_batteryVLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryVLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryVLabel, -100 );
lv_obj_set_y( ui_batteryVLabel, -125 );
lv_obj_set_align( ui_batteryVLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryVLabel,"V");
lv_obj_clear_flag( ui_batteryVLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_batteryVLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batteryVLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryVLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryALabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_batteryALabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryALabel, 100 );
lv_obj_set_y( ui_batteryALabel, -125 );
lv_obj_set_align( ui_batteryALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryALabel,"A");
lv_obj_clear_flag( ui_batteryALabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_batteryALabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batteryALabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryALabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_startBatteryLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_startBatteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_startBatteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_startBatteryLabel, 0 );
lv_obj_set_y( ui_startBatteryLabel, 205 );
lv_obj_set_align( ui_startBatteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_startBatteryLabel,"AUXILIARY BATTERY");
lv_obj_clear_flag( ui_startBatteryLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_startBatteryLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_startBatteryLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_startBatteryLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aeIconBatteryScreen1 = lv_img_create(ui_batteryScreen);
lv_img_set_src(ui_aeIconBatteryScreen1, &ui_img_ae_white_128_png);
lv_obj_set_width( ui_aeIconBatteryScreen1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aeIconBatteryScreen1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_aeIconBatteryScreen1, 0 );
lv_obj_set_y( ui_aeIconBatteryScreen1, -145 );
lv_obj_set_align( ui_aeIconBatteryScreen1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_aeIconBatteryScreen1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_aeIconBatteryScreen1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_aeIconBatteryScreen1,150);

ui_Image1 = lv_img_create(ui_batteryScreen);
lv_img_set_src(ui_Image1, &ui_img_2056808699);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, 150 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,200);

ui_BatteryTime = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_BatteryTime, 210);
lv_obj_set_height( ui_BatteryTime, 28);
lv_obj_set_x( ui_BatteryTime, 0 );
lv_obj_set_y( ui_BatteryTime, 60 );
lv_obj_set_align( ui_BatteryTime, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_BatteryTime,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_BatteryTime,"> 7 days");
lv_obj_clear_flag( ui_BatteryTime, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_BatteryTime, LV_DIR_HOR);
lv_obj_set_style_text_color(ui_BatteryTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatteryTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BatteryTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatteryTime, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SOCLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_SOCLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SOCLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SOCLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SOCLabel,"100%");
lv_obj_clear_flag( ui_SOCLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SOCLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SOCLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_SOCLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SOCLabel, &ui_font_AE64BOLD, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_meshIndicator = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_meshIndicator, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_meshIndicator, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_meshIndicator, 0 );
lv_obj_set_y( ui_meshIndicator, -64 );
lv_obj_set_align( ui_meshIndicator, LV_ALIGN_CENTER );
lv_label_set_text(ui_meshIndicator,"*");
lv_obj_clear_flag( ui_meshIndicator, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_meshIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_meshIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_meshIndicator, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarDayLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_BarDayLabel, 80);
lv_obj_set_height( ui_BarDayLabel, 31);
lv_obj_set_x( ui_BarDayLabel, -135 );
lv_obj_set_y( ui_BarDayLabel, 60 );
lv_obj_set_align( ui_BarDayLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_BarDayLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_BarDayLabel,"-5");
lv_obj_clear_flag( ui_BarDayLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_BarDayLabel, LV_DIR_HOR);
lv_obj_set_style_text_color(ui_BarDayLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BarDayLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BarDayLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BarDayLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarDayBottomLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_BarDayBottomLabel, 80);
lv_obj_set_height( ui_BarDayBottomLabel, 31);
lv_obj_set_x( ui_BarDayBottomLabel, -130 );
lv_obj_set_y( ui_BarDayBottomLabel, 90 );
lv_obj_set_align( ui_BarDayBottomLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_BarDayBottomLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_BarDayBottomLabel,"Wh/d");
lv_obj_clear_flag( ui_BarDayBottomLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_BarDayBottomLabel, LV_DIR_HOR);
lv_obj_set_style_text_color(ui_BarDayBottomLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BarDayBottomLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BarDayBottomLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BarDayBottomLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarWeekLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_BarWeekLabel, 80);
lv_obj_set_height( ui_BarWeekLabel, 31);
lv_obj_set_x( ui_BarWeekLabel, 135 );
lv_obj_set_y( ui_BarWeekLabel, 60 );
lv_obj_set_align( ui_BarWeekLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_BarWeekLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_BarWeekLabel,"100");
lv_obj_clear_flag( ui_BarWeekLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_BarWeekLabel, LV_DIR_HOR);
lv_obj_set_style_text_color(ui_BarWeekLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BarWeekLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BarWeekLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BarWeekLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarWeekBottomLabel = lv_label_create(ui_batteryScreen);
lv_obj_set_width( ui_BarWeekBottomLabel, 80);
lv_obj_set_height( ui_BarWeekBottomLabel, 31);
lv_obj_set_x( ui_BarWeekBottomLabel, 130 );
lv_obj_set_y( ui_BarWeekBottomLabel, 90 );
lv_obj_set_align( ui_BarWeekBottomLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_BarWeekBottomLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_BarWeekBottomLabel,"Wh/w");
lv_obj_clear_flag( ui_BarWeekBottomLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_BarWeekBottomLabel, LV_DIR_HOR);
lv_obj_set_style_text_color(ui_BarWeekBottomLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BarWeekBottomLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BarWeekBottomLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BarWeekBottomLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_aeIconBatteryScreen1, ui_event_aeIconBatteryScreen1, LV_EVENT_ALL, NULL);

}

void ui_batteryScreen_screen_destroy(void)
{
   if (ui_batteryScreen) lv_obj_del(ui_batteryScreen);

// NULL screen variables
ui_batteryScreen= NULL;
ui_SBattVArc= NULL;
ui_SA1Arc= NULL;
ui_battVLabelSensor= NULL;
ui_battALabelSensor= NULL;
ui_batteryVLabel= NULL;
ui_batteryALabel= NULL;
ui_startBatteryLabel= NULL;
ui_aeIconBatteryScreen1= NULL;
ui_Image1= NULL;
ui_BatteryTime= NULL;
ui_SOCLabel= NULL;
ui_meshIndicator= NULL;
ui_BarDayLabel= NULL;
ui_BarDayBottomLabel= NULL;
ui_BarWeekLabel= NULL;
ui_BarWeekBottomLabel= NULL;

}
