// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef UI_BOOTINITIALSCREEN_H
#define UI_BOOTINITIALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_bootInitialScreen
extern void ui_bootInitialScreen_screen_init(void);
extern void ui_bootInitialScreen_screen_destroy(void);
extern lv_obj_t *ui_bootInitialScreen;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_feedbackLabel;
extern void ui_event_wifiIcon( lv_event_t * e);
extern lv_obj_t *ui_wifiIcon;
extern void ui_event_settingsIcon( lv_event_t * e);
extern lv_obj_t *ui_settingsIcon;
extern void ui_event_aeLandingIcon( lv_event_t * e);
extern lv_obj_t *ui_aeLandingIcon;
extern lv_obj_t *ui_SSIDLabel;
extern void ui_event_SSIDInputText( lv_event_t * e);
extern lv_obj_t *ui_SSIDInputText;
extern lv_obj_t *ui_SSIDPasswordLabel;
extern void ui_event_SSIDPasswordInputText( lv_event_t * e);
extern lv_obj_t *ui_SSIDPasswordInputText;
extern void ui_event_Keyboard( lv_event_t * e);
extern lv_obj_t *ui_Keyboard;
extern void ui_event_landingBackButton( lv_event_t * e);
extern lv_obj_t *ui_landingBackButton;
extern lv_obj_t *ui_aeLandingBottomLabel;
extern lv_obj_t *ui_aeLandingBottomIcon;
extern lv_obj_t *ui_VictronCheckbox;
extern lv_obj_t *ui_VictronCheckboxLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_VictronCheckbox;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

