// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void toggleWiFi(lv_event_t * e);
void settingsButtonPressedFunction(lv_event_t * e);
void configureTPMS(lv_event_t * e);
void landingBackButtonPressedFunction(lv_event_t * e);
void cycleTyreDataFn(lv_event_t * e);
void savePressuresFn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
