// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "ui.h"
#include "Arduino.h"
#include "../../src/shared_data.h"
#include <string.h> // For strcmp

extern bool wifiSetToOn;
extern bool settingsState;
extern bool syncFlash;
extern bool connectWiFi;
extern bool validLocation;

void toggleWiFi(lv_event_t *e)
{
	if (!settingsState) // on the landing page, AKA not in settings
	{
		LV_LOG_USER("CHECKING IF WIFI CAN BE TURNED ON");

		// Check if WiFi is properly configured
		if (PWD_c == NULL || strcmp(PWD_c, "none") == 0 || strcmp(PWD_c, "no_p_pwd") == 0)
		{
			LV_LOG_USER("WIFI NOT CONFIGURED - REDIRECTING TO SETTINGS");
			settingsButtonPressedFunction(e);
			toggleWiFi(e); // Recursive call to enter the WiFi settings sub-menu
			_ui_label_set_property(ui_feedbackLabel, _UI_LABEL_PROPERTY_TEXT, "CONFIGURE WIFI");
			return;
		}

		if (wifiSetToOn)
		{
			lv_img_set_src(ui_wifiIcon, &ui_img_2104900491); // WiFi off
			LV_LOG_USER("WIFI SET TO OFF");
			wifiSetToOn = false;
			syncFlash = true;
		}
		else
		{
			LV_LOG_USER("WIFI CONFIGURED AND ON");
			wifiSetToOn = true;
			connectWiFi = true;
			lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);
			if (SSID_c != NULL) LV_LOG_USER("%s", SSID_c);
			if (PWD_c != NULL) LV_LOG_USER("%s", PWD_c);
			lv_label_set_text(ui_feedbackLabel, "");
			lv_img_set_src(ui_wifiIcon, &ui_img_807091229); // WiFi on
			syncFlash = true;
		}
	}
	else
	{
		LV_LOG_USER("WIFI SETTINGS PRESSED");
		;

		lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_wifiIcon, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_aeLandingIcon, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_settingsIcon, LV_OBJ_FLAG_HIDDEN);

		lv_obj_clear_flag(ui_SSIDLabel, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_SSIDInputText, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_SSIDPasswordInputText, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_SSIDPasswordLabel, LV_OBJ_FLAG_HIDDEN);

		lv_obj_set_y(ui_feedbackLabel, -170);
		_ui_label_set_property(ui_feedbackLabel, _UI_LABEL_PROPERTY_TEXT, "WiFi SETTINGS: ");
	}
}

extern void startPairingProcess(void);

void settingsButtonPressedFunction(lv_event_t *e)
{
	LV_LOG_USER("SETTINGS BUTTON PRESSED");
	if (settingsState)
	{
		LV_LOG_USER("PAIRING REQUESTED");
        // Hide icons for Pairing Mode
        lv_obj_add_flag(ui_wifiIcon, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_aeLandingIcon, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_settingsIcon, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_feedbackLabel, LV_OBJ_FLAG_HIDDEN);
        
        // Show Spinner
        // lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN); // Spinner causes artifacts (black square) over QR code


		startPairingProcess();
		return;
	}

	settingsState = true;
	if (settingsState)
	{
		// lv_obj_add_flag(ui_wifiIcon, LV_OBJ_FLAG_HIDDEN);
		lv_img_set_src(ui_wifiIcon, &ui_img_943648365);       // WiFi settings
		lv_img_set_src(ui_aeLandingIcon, &ui_img_1749172309); // Gauge settings
		lv_img_set_src(ui_settingsIcon, &ui_img_2022370193);  // ESP now settings

		lv_obj_add_flag(ui_aeLandingBottomLabel, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_aeLandingBottomIcon, LV_OBJ_FLAG_HIDDEN);

		_ui_label_set_property(ui_feedbackLabel, _UI_LABEL_PROPERTY_TEXT, "SETTINGS: ");
		lv_obj_clear_flag(ui_landingBackButton, LV_OBJ_FLAG_HIDDEN);
	}
}

void landingBackButtonPressedFunction(lv_event_t *e)
{
	if (settingsState)
	{
		LV_LOG_USER("BACK BUTTON PRESSED");
        // Invalidate screen to clear any direct drawing (like QR code)
        lv_obj_invalidate(lv_scr_act());

		lv_obj_add_flag(ui_SSIDInputText, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SSIDPasswordInputText, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SSIDLabel, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SSIDPasswordLabel, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_landingBackButton, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_aeLandingBottomIcon, LV_OBJ_FLAG_HIDDEN);

		lv_obj_clear_flag(ui_wifiIcon, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_aeLandingIcon, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_settingsIcon, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_feedbackLabel, LV_OBJ_FLAG_HIDDEN);
        
        // Hide Spinner
        lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);

		lv_obj_clear_flag(ui_aeLandingBottomLabel, LV_OBJ_FLAG_HIDDEN);

		lv_img_set_src(ui_settingsIcon, &ui_img_501072417);			// settings Icon
		lv_img_set_src(ui_aeLandingIcon, &ui_img_ae_white_128_png); // AE Landing Icon

		lv_obj_set_y(ui_feedbackLabel, -125);
		lv_obj_set_y(ui_SSIDLabel, -90);
		lv_obj_set_y(ui_SSIDInputText, -58);
		lv_obj_set_y(ui_SSIDPasswordLabel, 15);
		lv_obj_set_y(ui_SSIDPasswordInputText, 48);

		_ui_label_set_property(ui_feedbackLabel, _UI_LABEL_PROPERTY_TEXT, "");

		if (wifiSetToOn)
		{
			lv_img_set_src(ui_wifiIcon, &ui_img_807091229); // WiFi on
		}
		else
		{
			lv_img_set_src(ui_wifiIcon, &ui_img_2104900491); // WiFi off
		}
        
        // Reset "Done" back to "Back" for next time
        if (ui_landingBackButton) {
            lv_label_set_text(ui_landingBackButton, "Back");
        }
	}
	settingsState = false;
}

extern void toggleRememberScreen();

void aeLandingIconFunction(lv_event_t *e)
{
	// "Gauge Settings" Icon Pressed
    if (settingsState) {
        toggleRememberScreen();
    }
}
