// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "ui.h"

bool wifiOffState = true;

void toggleWiFi(lv_event_t * e)
{
	wifiOffState = !wifiOffState;
	if (wifiOffState)
	{
		lv_img_set_src(ui_wifiIcon, &ui_img_2104900491);
	}
	else
	{
		lv_img_set_src(ui_wifiIcon, &ui_img_807091229);
	}
}
