// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef UI_TEMPERATURESCREEN_H
#define UI_TEMPERATURESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_temperatureScreen
extern void ui_temperatureScreen_screen_init(void);
extern void ui_temperatureScreen_screen_destroy(void);
extern lv_obj_t *ui_temperatureScreen;
extern lv_obj_t *ui_TempTempArc;
extern lv_obj_t *ui_TempSwingArc;
extern lv_obj_t *ui_TempNameLabel;
extern void ui_event_aeIconBatteryScreen2( lv_event_t * e);
extern lv_obj_t *ui_aeIconBatteryScreen2;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_TempBattSOCLabel;
extern lv_obj_t *ui_TempTempLabel;
extern lv_obj_t *ui_TempmeshIndicator;
extern lv_obj_t *ui_tempCentralLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

