// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "ui.h"

lv_obj_t *ui_tpmsScreen = NULL;lv_obj_t *ui_TempNameLabel1 = NULL;lv_obj_t *ui_aeIconBatteryScreen3 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_FLPSI = NULL;lv_obj_t *ui_tpmsIndicator = NULL;lv_obj_t *ui_FRPSI = NULL;lv_obj_t *ui_RRPSI = NULL;lv_obj_t *ui_RRPSI1 = NULL;
// event funtions
void ui_event_aeIconBatteryScreen3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      cycleTyreDataFn( e );
}
}

void ui_event_Image3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      savePressuresFn( e );
}
}

// build funtions

void ui_tpmsScreen_screen_init(void)
{
ui_tpmsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_tpmsScreen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_tpmsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tpmsScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_tpmsScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_tpmsScreen, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempNameLabel1 = lv_label_create(ui_tpmsScreen);
lv_obj_set_width( ui_TempNameLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempNameLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempNameLabel1, 0 );
lv_obj_set_y( ui_TempNameLabel1, 205 );
lv_obj_set_align( ui_TempNameLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempNameLabel1,"TPMS");
lv_obj_clear_flag( ui_TempNameLabel1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_TempNameLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempNameLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempNameLabel1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aeIconBatteryScreen3 = lv_img_create(ui_tpmsScreen);
lv_img_set_src(ui_aeIconBatteryScreen3, &ui_img_ae_white_128_png);
lv_obj_set_width( ui_aeIconBatteryScreen3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aeIconBatteryScreen3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_aeIconBatteryScreen3, 0 );
lv_obj_set_y( ui_aeIconBatteryScreen3, -145 );
lv_obj_set_align( ui_aeIconBatteryScreen3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_aeIconBatteryScreen3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_aeIconBatteryScreen3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_aeIconBatteryScreen3,150);

ui_Image3 = lv_img_create(ui_tpmsScreen);
lv_img_set_src(ui_Image3, &ui_img_699809084);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, 0 );
lv_obj_set_y( ui_Image3, 56 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,300);

ui_FLPSI = lv_label_create(ui_tpmsScreen);
lv_obj_set_width( ui_FLPSI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FLPSI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FLPSI, -123 );
lv_obj_set_y( ui_FLPSI, -15 );
lv_obj_set_align( ui_FLPSI, LV_ALIGN_CENTER );
lv_label_set_text(ui_FLPSI,"~");
lv_obj_clear_flag( ui_FLPSI, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_FLPSI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FLPSI, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_FLPSI, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FLPSI, &ui_font_AE64BOLD, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tpmsIndicator = lv_label_create(ui_tpmsScreen);
lv_obj_set_width( ui_tpmsIndicator, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tpmsIndicator, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tpmsIndicator, 0 );
lv_obj_set_y( ui_tpmsIndicator, -64 );
lv_obj_set_align( ui_tpmsIndicator, LV_ALIGN_CENTER );
lv_label_set_text(ui_tpmsIndicator,"*");
lv_obj_clear_flag( ui_tpmsIndicator, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_tpmsIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tpmsIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tpmsIndicator, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FRPSI = lv_label_create(ui_tpmsScreen);
lv_obj_set_width( ui_FRPSI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FRPSI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FRPSI, 123 );
lv_obj_set_y( ui_FRPSI, -15 );
lv_obj_set_align( ui_FRPSI, LV_ALIGN_CENTER );
lv_label_set_text(ui_FRPSI,"~");
lv_obj_clear_flag( ui_FRPSI, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_FRPSI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FRPSI, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_FRPSI, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FRPSI, &ui_font_AE64BOLD, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RRPSI = lv_label_create(ui_tpmsScreen);
lv_obj_set_width( ui_RRPSI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RRPSI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RRPSI, 123 );
lv_obj_set_y( ui_RRPSI, 115 );
lv_obj_set_align( ui_RRPSI, LV_ALIGN_CENTER );
lv_label_set_text(ui_RRPSI,"~");
lv_obj_clear_flag( ui_RRPSI, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_RRPSI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RRPSI, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_RRPSI, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RRPSI, &ui_font_AE64BOLD, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RRPSI1 = lv_label_create(ui_tpmsScreen);
lv_obj_set_width( ui_RRPSI1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RRPSI1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RRPSI1, -123 );
lv_obj_set_y( ui_RRPSI1, 115 );
lv_obj_set_align( ui_RRPSI1, LV_ALIGN_CENTER );
lv_label_set_text(ui_RRPSI1,"~");
lv_obj_clear_flag( ui_RRPSI1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_RRPSI1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RRPSI1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_RRPSI1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RRPSI1, &ui_font_AE64BOLD, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_aeIconBatteryScreen3, ui_event_aeIconBatteryScreen3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);

}

void ui_tpmsScreen_screen_destroy(void)
{
   if (ui_tpmsScreen) lv_obj_del(ui_tpmsScreen);

// NULL screen variables
ui_tpmsScreen= NULL;
ui_TempNameLabel1= NULL;
ui_aeIconBatteryScreen3= NULL;
ui_Image3= NULL;
ui_FLPSI= NULL;
ui_tpmsIndicator= NULL;
ui_FRPSI= NULL;
ui_RRPSI= NULL;
ui_RRPSI1= NULL;

}
