// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#include "ui.h"

lv_obj_t *ui_temperatureScreen = NULL;lv_obj_t *ui_TempTempArc = NULL;lv_obj_t *ui_TempSwingArc = NULL;lv_obj_t *ui_TempNameLabel = NULL;lv_obj_t *ui_aeIconBatteryScreen2 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_TempBattSOCLabel = NULL;lv_obj_t *ui_TempTempLabel = NULL;lv_obj_t *ui_TempmeshIndicator = NULL;lv_obj_t *ui_tempCentralLabel = NULL;
// event funtions
void ui_event_aeIconBatteryScreen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_bootInitialScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_bootInitialScreen_screen_init);
}
}

// build funtions

void ui_temperatureScreen_screen_init(void)
{
ui_temperatureScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_temperatureScreen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_temperatureScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temperatureScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_temperatureScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_temperatureScreen, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempTempArc = lv_arc_create(ui_temperatureScreen);
lv_obj_set_width( ui_TempTempArc, 480);
lv_obj_set_height( ui_TempTempArc, 480);
lv_obj_set_align( ui_TempTempArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TempTempArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_TempTempArc, -10,10);
lv_arc_set_value(ui_TempTempArc, 35);
lv_arc_set_bg_angles(ui_TempTempArc,45,315);
lv_arc_set_mode(ui_TempTempArc, LV_ARC_MODE_SYMMETRICAL);
lv_arc_set_rotation(ui_TempTempArc,90);
lv_obj_set_style_arc_color(ui_TempTempArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TempTempArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_TempTempArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TempTempArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TempTempArc, 30, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TempTempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempTempArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TempSwingArc = lv_arc_create(ui_temperatureScreen);
lv_obj_set_width( ui_TempSwingArc, 415);
lv_obj_set_height( ui_TempSwingArc, 415);
lv_obj_set_align( ui_TempSwingArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TempSwingArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_TempSwingArc, -5,5);
lv_arc_set_value(ui_TempSwingArc, 3);
lv_arc_set_bg_angles(ui_TempSwingArc,45,315);
lv_arc_set_mode(ui_TempSwingArc, LV_ARC_MODE_SYMMETRICAL);
lv_arc_set_rotation(ui_TempSwingArc,90);
lv_obj_set_style_arc_color(ui_TempSwingArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TempSwingArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_TempSwingArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TempSwingArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TempSwingArc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TempSwingArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempSwingArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TempNameLabel = lv_label_create(ui_temperatureScreen);
lv_obj_set_width( ui_TempNameLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempNameLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempNameLabel, 0 );
lv_obj_set_y( ui_TempNameLabel, 205 );
lv_obj_set_align( ui_TempNameLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempNameLabel,"LEFT FRIDGE");
lv_obj_clear_flag( ui_TempNameLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_TempNameLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempNameLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempNameLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aeIconBatteryScreen2 = lv_img_create(ui_temperatureScreen);
lv_img_set_src(ui_aeIconBatteryScreen2, &ui_img_ae_white_128_png);
lv_obj_set_width( ui_aeIconBatteryScreen2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aeIconBatteryScreen2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_aeIconBatteryScreen2, 0 );
lv_obj_set_y( ui_aeIconBatteryScreen2, -145 );
lv_obj_set_align( ui_aeIconBatteryScreen2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_aeIconBatteryScreen2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_aeIconBatteryScreen2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_zoom(ui_aeIconBatteryScreen2,150);

ui_Image2 = lv_img_create(ui_temperatureScreen);
lv_img_set_src(ui_Image2, &ui_img_1965588767);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, 0 );
lv_obj_set_y( ui_Image2, 150 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,180);

ui_TempBattSOCLabel = lv_label_create(ui_temperatureScreen);
lv_obj_set_width( ui_TempBattSOCLabel, 300);
lv_obj_set_height( ui_TempBattSOCLabel, 28);
lv_obj_set_x( ui_TempBattSOCLabel, 0 );
lv_obj_set_y( ui_TempBattSOCLabel, 60 );
lv_obj_set_align( ui_TempBattSOCLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_TempBattSOCLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_TempBattSOCLabel,"Sensor Battery: 100%");
lv_obj_add_flag( ui_TempBattSOCLabel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( ui_TempBattSOCLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_TempBattSOCLabel, LV_DIR_HOR);
lv_obj_set_style_text_color(ui_TempBattSOCLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempBattSOCLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TempBattSOCLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempBattSOCLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempTempLabel = lv_label_create(ui_temperatureScreen);
lv_obj_set_width( ui_TempTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TempTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempTempLabel,"4C");
lv_obj_clear_flag( ui_TempTempLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_TempTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempTempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_TempTempLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempTempLabel, &ui_font_AE64BOLD, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempmeshIndicator = lv_label_create(ui_temperatureScreen);
lv_obj_set_width( ui_TempmeshIndicator, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempmeshIndicator, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempmeshIndicator, 0 );
lv_obj_set_y( ui_TempmeshIndicator, -64 );
lv_obj_set_align( ui_TempmeshIndicator, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempmeshIndicator,"*");
lv_obj_clear_flag( ui_TempmeshIndicator, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_TempmeshIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempmeshIndicator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempmeshIndicator, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempCentralLabel = lv_label_create(ui_temperatureScreen);
lv_obj_set_width( ui_tempCentralLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempCentralLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_tempCentralLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempCentralLabel,"");
lv_obj_add_flag( ui_tempCentralLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_tempCentralLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_tempCentralLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempCentralLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_tempCentralLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tempCentralLabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_aeIconBatteryScreen2, ui_event_aeIconBatteryScreen2, LV_EVENT_ALL, NULL);

}

void ui_temperatureScreen_screen_destroy(void)
{
   if (ui_temperatureScreen) lv_obj_del(ui_temperatureScreen);

// NULL screen variables
ui_temperatureScreen= NULL;
ui_TempTempArc= NULL;
ui_TempSwingArc= NULL;
ui_TempNameLabel= NULL;
ui_aeIconBatteryScreen2= NULL;
ui_Image2= NULL;
ui_TempBattSOCLabel= NULL;
ui_TempTempLabel= NULL;
ui_TempmeshIndicator= NULL;
ui_tempCentralLabel= NULL;

}
