// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: ae_52mm_gauge

#ifndef UI_TPMSSCREEN_H
#define UI_TPMSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tpmsScreen
extern void ui_tpmsScreen_screen_init(void);
extern void ui_tpmsScreen_screen_destroy(void);
extern lv_obj_t *ui_tpmsScreen;
extern lv_obj_t *ui_TempNameLabel1;
extern void ui_event_aeIconBatteryScreen3( lv_event_t * e);
extern lv_obj_t *ui_aeIconBatteryScreen3;
extern void ui_event_Image3( lv_event_t * e);
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_FLPSI;
extern lv_obj_t *ui_tpmsIndicator;
extern lv_obj_t *ui_FRPSI;
extern lv_obj_t *ui_RRPSI;
extern lv_obj_t *ui_RRPSI1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

